# Una competencia en Kaggle

In [4]:
import os
import kagglehub
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

In [3]:
token = 'KGAT_817f3ab935a01b0584dff2df96401376'

In [5]:
kagglehub.login()

VBox(children=(HTML(value='<center> <img\nsrc=https://www.kaggle.com/static/images/site-logo.png\nalt=\'Kaggle…

Kaggle credentials set.
Kaggle credentials successfully validated.

In [6]:
download_path = kagglehub.competition_download('gsis-ml-society-section-b')

Downloading to /root/.cache/kagglehub/competitions/gsis-ml-society-section-b.archive...

100%|██████████| 551k/551k [00:00<00:00, 123MB/s]

Extracting files...

In [7]:
print(os.listdir(download_path))

['train.csv', 'test.csv', 'sample_submission.csv']

In [21]:
train_base = pd.read_csv(os.path.join(download_path, 'train.csv'))
test_base = pd.read_csv(os.path.join(download_path, 'test.csv'))

In [22]:
train_base.head()

   id Sex  Length  Diameter  ...  Shucked Weight  Viscera Weight  Shell Weight  Age
0   0   I  1.0000    0.7625  ...        3.940580        1.771844      2.834950  8.0
1   1   M  0.9500    0.6750  ...        2.749901        1.289902      1.842718  7.0
2   2   M  1.4250    1.1250  ...       12.346207        7.243297      8.363103  9.0
3   3   F  1.5125    1.1875  ...       11.878440        5.925046      6.803880  9.0
4   4   I  1.2125    0.9375  ...        7.044851        2.905824      4.394172  9.0

[5 rows x 10 columns]

In [10]:
train_base.drop(['id'], axis=1, inplace=True)
test_base.drop(['id'], axis=1, inplace=True)

In [12]:
train_base['Sex'] = train_base['Sex'].astype('category').cat.codes
test_base['Sex'] = test_base['Sex'].astype('category').cat.codes

In [16]:
X = train_base.drop(['Age'], axis=1)
y = train_base['Age']

display(X.head())
display(y.head())

   Sex  Length  Diameter  ...  Shucked Weight  Viscera Weight  Shell Weight
0    1  1.0000    0.7625  ...        3.940580        1.771844      2.834950
1    2  0.9500    0.6750  ...        2.749901        1.289902      1.842718
2    2  1.4250    1.1250  ...       12.346207        7.243297      8.363103
3    0  1.5125    1.1875  ...       11.878440        5.925046      6.803880
4    1  1.2125    0.9375  ...        7.044851        2.905824      4.394172

[5 rows x 8 columns]

0    8.0
1    7.0
2    9.0
3    9.0
4    9.0
Name: Age, dtype: float64

In [17]:
rf = RandomForestRegressor(n_estimators=500, max_features=0.5, min_samples_leaf=2, n_jobs=-1)

In [18]:
rf.fit(X, y)

RandomForestRegressor(max_features=0.5, min_samples_leaf=2, n_estimators=500,
                      n_jobs=-1)

In [20]:
y_test = rf.predict(test_base)

In [23]:
sub = pd.DataFrame({'id': test_base['id'], 'Age': y_test})

In [25]:
sub.to_csv('submission.csv', index=False)